SCHEMA_V3 = [
    {"key": "age_years", "label": "Edad", "unit": "anos", "level": "essential", "input_type": "number", "domain": "context", "convert_group": None},
    {
        "key": "sex",
        "label": "Sexo biológico",
        "unit": "categorico",
        "level": "essential",
        "input_type": "select",
        "domain": "context",
        "convert_group": None,
        "options": ["M", "F"],
        "option_labels": {"M": "Varón", "F": "Mujer"},
    },

    {"key": "glucose_mg_dl", "label": "Glucosa", "unit": "mg/dL", "level": "essential", "input_type": "number", "domain": "glucose", "convert_group": "glucose"},
    {"key": "hba1c_pct", "label": "HbA1c", "unit": "%", "level": "essential", "input_type": "number", "domain": "glucose", "convert_group": None},
    {"key": "insulin_uIU_ml", "label": "Insulina", "unit": "uIU/mL", "level": "precision", "input_type": "number", "domain": "glucose", "convert_group": None},

    {"key": "chol_total_mg_dl", "label": "Colesterol total", "unit": "mg/dL", "level": "precision", "input_type": "number", "domain": "lipids", "convert_group": "lipids"},
    {"key": "ldl_mg_dl", "label": "LDL", "unit": "mg/dL", "level": "essential", "input_type": "number", "domain": "lipids", "convert_group": "lipids"},
    {"key": "hdl_mg_dl", "label": "HDL", "unit": "mg/dL", "level": "essential", "input_type": "number", "domain": "lipids", "convert_group": "lipids"},
    {"key": "triglycerides_mg_dl", "label": "Triglicéridos", "unit": "mg/dL", "level": "essential", "input_type": "number", "domain": "lipids", "convert_group": "triglycerides"},

    {"key": "hb_g_dl", "label": "Hemoglobina", "unit": "g/dL", "level": "essential", "input_type": "number", "domain": "hematology", "convert_group": None},
    {"key": "mcv_fl", "label": "VCM (MCV)", "unit": "fL", "level": "essential", "input_type": "number", "domain": "hematology", "convert_group": None},
    {"key": "rdw_pct", "label": "RDW", "unit": "%", "level": "essential", "input_type": "number", "domain": "hematology", "convert_group": None},
    {"key": "ferritin_ng_ml", "label": "Ferritina", "unit": "ng/mL", "level": "essential", "input_type": "number", "domain": "hematology", "convert_group": None},

    {"key": "alt_u_l", "label": "ALT", "unit": "U/L", "level": "essential", "input_type": "number", "domain": "liver", "convert_group": None},
    {"key": "ast_u_l", "label": "AST", "unit": "U/L", "level": "essential", "input_type": "number", "domain": "liver", "convert_group": None},
    {"key": "creatinine_mg_dl", "label": "Creatinina", "unit": "mg/dL", "level": "essential", "input_type": "number", "domain": "kidney", "convert_group": None},

    {"key": "hscrp_mg_l", "label": "hsCRP / PCR", "unit": "mg/L", "level": "precision", "input_type": "number", "domain": "inflammation", "convert_group": None},
    {"key": "uric_acid_mg_dl", "label": "Ácido úrico", "unit": "mg/dL", "level": "precision", "input_type": "number", "domain": "kidney", "convert_group": None},
    {"key": "ggt_u_l", "label": "GGT", "unit": "U/L", "level": "precision", "input_type": "number", "domain": "liver", "convert_group": None},
    {"key": "vitb12_pg_ml", "label": "Vitamina B12", "unit": "pg/mL", "level": "precision", "input_type": "number", "domain": "hematology", "convert_group": None},
    {"key": "folate_ng_ml", "label": "Folato", "unit": "ng/mL", "level": "precision", "input_type": "number", "domain": "hematology", "convert_group": None},
    {"key": "albumin_g_dl", "label": "Albúmina sérica", "unit": "g/dL", "level": "precision", "input_type": "number", "domain": "protein", "convert_group": None},
    {"key": "platelets_x10_3_uL", "label": "Plaquetas", "unit": "x10^3/uL", "level": "precision", "input_type": "number", "domain": "hematology", "convert_group": None},
    {"key": "tsh_mIU_l", "label": "TSH", "unit": "mIU/L", "level": "precision", "input_type": "number", "domain": "context", "convert_group": None},

    {"key": "bmi_kg_m2", "label": "BMI", "unit": "kg/m2", "level": "advanced", "input_type": "number", "domain": "context", "convert_group": None},
    {"key": "waist_cm", "label": "Cintura", "unit": "cm", "level": "advanced", "input_type": "number", "domain": "context", "convert_group": None},
    {"key": "esr_mm_h", "label": "VSG (ESR)", "unit": "mm/h", "level": "advanced", "input_type": "number", "domain": "inflammation", "convert_group": None},
    {"key": "fibrinogen_mg_dl", "label": "Fibrinógeno", "unit": "mg/dL", "level": "advanced", "input_type": "number", "domain": "inflammation", "convert_group": None},
    {"key": "wbc_x10_3_mm3", "label": "Leucocitos", "unit": "x10^3/mm3", "level": "advanced", "input_type": "number", "domain": "inflammation", "convert_group": None},
    {"key": "neut_abs_x10_3_mm3", "label": "Neutrófilos abs", "unit": "x10^3/mm3", "level": "advanced", "input_type": "number", "domain": "inflammation", "convert_group": None},
    {"key": "lymph_abs_x10_3_mm3", "label": "Linfocitos abs", "unit": "x10^3/mm3", "level": "advanced", "input_type": "number", "domain": "inflammation", "convert_group": None},
    {"key": "hct_pct", "label": "Hematocrito", "unit": "%", "level": "advanced", "input_type": "number", "domain": "hematology", "convert_group": None},
    {"key": "rbc_x10_6_mm3", "label": "Hematíes", "unit": "x10^6/mm3", "level": "advanced", "input_type": "number", "domain": "hematology", "convert_group": None},
    {"key": "iron_ug_dl", "label": "Hierro", "unit": "mcg/dL", "level": "advanced", "input_type": "number", "domain": "hematology", "convert_group": None},
    {"key": "transferrin_mg_dl", "label": "Transferrina", "unit": "mg/dL", "level": "advanced", "input_type": "number", "domain": "hematology", "convert_group": None},
    {"key": "transferrin_sat_pct", "label": "Sat. transferrina", "unit": "%", "level": "advanced", "input_type": "number", "domain": "hematology", "convert_group": None},
    {"key": "tibc_ug_dl", "label": "TIBC", "unit": "mcg/dL", "level": "advanced", "input_type": "number", "domain": "hematology", "convert_group": None},
    {"key": "alp_u_l", "label": "ALP", "unit": "U/L", "level": "advanced", "input_type": "number", "domain": "liver", "convert_group": None},
    {"key": "bilirubin_total_mg_dl", "label": "Bilirrubina total", "unit": "mg/dL", "level": "advanced", "input_type": "number", "domain": "liver", "convert_group": None},
    {"key": "egfr_ml_min_1_73m2", "label": "eGFR", "unit": "mL/min/1.73m2", "level": "advanced", "input_type": "number", "domain": "kidney", "convert_group": None},
    {"key": "urea_mg_dl", "label": "Urea", "unit": "mg/dL", "level": "advanced", "input_type": "number", "domain": "kidney", "convert_group": None},
    {"key": "apob_mg_dl", "label": "ApoB", "unit": "mg/dL", "level": "advanced", "input_type": "number", "domain": "lipids", "convert_group": "lipids"},
    {"key": "ft4_ng_dl", "label": "T4 libre (FT4)", "unit": "ng/dL", "level": "advanced", "input_type": "number", "domain": "context", "convert_group": None},
]